export const PRODUCTS = [
  {
    id: 'groom-1',
    name: 'Grand Ivory Sherwani',
    category: 'Men',
    price: 45000,
    image: '/images/products/1774861981073groom-essentials.webp',
    badge: 'Heritage Classic',
    description: 'A timeless ivory sherwani adorned with intricate tilla embroidery, handcrafted for the modern groom. Made from luxurious raw silk, featuring custom hand-forged metallic brass buttons and a sharp contemporary collar silhouette.',
    highlights: ['100% Premium Raw Silk', 'Sovereign Brass Buttons', 'Handcrafted Custom Quilting', 'Comes with matching Churidar'],
    designer: 'Manyavar Mohey',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    isNew: false,
    celebrityCloset: true,
    occasions: ['Wedding'],
    discount: 15
  },
  {
    id: 'groom-2',
    name: 'The Kurta Jacket Edit',
    category: 'Men',
    price: 22000,
    image: '/images/whatsnew/1774861981073groom-essentials.webp',
    badge: 'Popular Choice',
    description: 'A bespoke silk kurta paired with a highly structured textured bundi jacket. Finished with a subtle self-pattern weave that catches the light beautifully at evening engagements.',
    highlights: ['Micro-textured Khadi Silk Blend', 'Pocket Square Accent Included', 'Mandarin Collar Styling', 'Mid-thigh length classic drape'],
    designer: 'Playfair Mohey',
    sizes: ['S', 'M', 'L', 'XL'],
    isNew: true,
    celebrityCloset: false,
    occasions: ['Haldi', 'Mehendi'],
    discount: 10
  },
  {
    id: 'groom-3',
    name: 'Deep Tone Bandhgala',
    category: 'Men',
    price: 38000,
    image: '/images/occasions/1774948127503reception.avif',
    badge: 'Midnight Royal',
    description: 'Exquisitely structured bandhgala suit in a deep charcoal burgundy hue. Intended for absolute presence, it couples classic imperial cuts with sophisticated contemporary minimalist tailoring.',
    highlights: ['Royal Premium Italian Crepe', 'Detailed hand-stitched piping', 'Sleek concealed functional pockets', 'Imperial slim-fit trouser set'],
    designer: 'Ridhi Mehra',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    isNew: false,
    celebrityCloset: true,
    occasions: ['Reception'],
    discount: 20
  },
  {
    id: 'groom-4',
    name: 'Mirrorwork Festive Edit',
    category: 'Men',
    price: 28000,
    image: '/images/whatsnew/1774861981073groom-essentials.webp',
    badge: 'New Arrival',
    description: 'An outstanding festive design bearing precise mirror thread detailing on the yoke. Paired seamlessly with a soft premium georgette underlayer for supreme all-day movement comfort.',
    highlights: ['Reflective mirror motif layout', 'Breathable lightweight construction', 'Georgette & Viscose blend', 'Slightly flared modern hemline'],
    designer: 'Aza Editorials',
    sizes: ['M', 'L', 'XL'],
    isNew: true,
    celebrityCloset: false,
    occasions: ['Mehendi', 'Haldi'],
    discount: 15
  },
  {
    id: 'women-1',
    name: 'Romantic Fuchsia Couture Lehenga',
    category: 'Lehengas',
    price: 125000,
    image: '/images/products/1773662540730multi-coloured-lehenga-edit.webp',
    badge: 'Couture Masterpiece',
    description: 'Enchanting romantic couture tailored with a modern spirit. This exquisite fuchsia pink bridal set highlights heavy hand-done Resham work, floral motifs, and a spectacular sheer silk dupatta.',
    highlights: ['Pure Hand-done Zardozi', 'Premium Chanderi Silk fabric base', 'Signature Ridhi Mehra styling with modern cutouts', 'Includes custom embellished corset blouse'],
    designer: 'Ridhi Mehra',
    sizes: ['XS', 'S', 'M', 'L'],
    isNew: false,
    celebrityCloset: true,
    occasions: ['Wedding'],
    discount: 25
  },
  {
    id: 'women-2',
    name: 'Emerald Heritage Anarkali',
    category: 'Women',
    price: 64000,
    image: '/images/whatsnew/1773662608426statement-sharara-sets.webp',
    badge: 'Heritage Campaign',
    description: 'A deep forest emerald green masterpiece illustrating ancestral weaving. Adorned with delicate vintage gold thread border details that define understated heritage elegance.',
    highlights: ['Handwoven Banarasi Silk trim', 'Chiffon sheer long length flow', 'Comfort fit empire cut', 'Comes with heavily matching churidar'],
    designer: 'Ridhi Mehra',
    sizes: ['S', 'M', 'L', 'XL'],
    isNew: true,
    celebrityCloset: false,
    occasions: ['Mehendi', 'Reception'],
    discount: 10
  },
  {
    id: 'women-3',
    name: 'Zardozi Bridal Saree',
    category: 'Wedding',
    price: 89000,
    image: '/images/hero/1774946941021the-wedding.avif',
    badge: 'Bridal Selection',
    description: 'An ancestral crimson wedding saree woven inside authentic Banaras handlooms. Every centimeter reflects the magnificent master weaving that honors traditional craftsmanship with a majestic drape.',
    highlights: ['Royal crimson color signature', 'Real gold polished tilla threads', 'Includes custom matching blouse material', 'Weighted luxury fall draping'],
    designer: 'Manyavar Mohey',
    sizes: ['Free Size'],
    isNew: false,
    celebrityCloset: true,
    occasions: ['Wedding'],
    discount: 15
  },
  {
    id: 'kids-1',
    name: 'Princes Miniature Velvet Sherwani',
    category: 'Kids',
    price: 15500,
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
    badge: 'Kids Royal',
    description: 'Premium soft velvet mini sherwani tailored purposefully for absolute comfort and unrestricted movement. Outfitted with safe soft linings and kid-friendly zip-closure back styling.',
    highlights: ['Extremely child-safe organic cotton lining', 'No-scratch gold elements', 'Elasticated soft pajama trousers', 'Pre-draped side pocket styling'],
    designer: 'Vedant Fashions',
    sizes: ['4-5 Yrs', '6-7 Yrs', '8-9 Yrs', '10-11 Yrs'],
    isNew: false,
    celebrityCloset: false,
    occasions: ['Wedding', 'Reception'],
    discount: 5
  },
  {
    id: 'kids-2',
    name: 'Festive Pastel Gown Set',
    category: 'Kids',
    price: 12800,
    image: 'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?auto=format&fit=crop&w=800&q=80',
    badge: 'Festive Little Ones',
    description: 'A gorgeous ethnic tiered pastel peach dress for girls. Styled using premium soft tissue georgette, complete with lightweight floral appliques and standard matching sheer organza dupatta.',
    highlights: ['Micro-jersey inner top layers', 'Allergy-free synthetic borders', 'Lightweight and wrinkle-proof', 'Comes with adjustable satin belt sash'],
    designer: 'Aza Editorials',
    sizes: ['4-5 Yrs', '6-7 Yrs', '8-9 Yrs'],
    isNew: true,
    celebrityCloset: false,
    occasions: ['Mehendi', 'Haldi'],
    discount: 20
  },
  {
    id: 'designer-item-1',
    name: 'Abstract Contemporary Lehenga Set',
    category: 'Designers',
    price: 140000,
    image: '/images/whatsnew/1773662540730multi-coloured-lehenga-edit.webp',
    badge: 'Designer Elite',
    description: 'A rare collaboration design that infuses minimalist patterns into traditional lehenga shapes. Truly destined for fashion-forward weddings where artistic distinction is non-negotiable.',
    highlights: ['Exclusively handmade to order', 'Premium silk organza multilayer skirt', 'Structured modern bustier corset', 'Signed by Chef de Design Ridhi Mehra'],
    designer: 'Ridhi Mehra',
    sizes: ['S', 'M', 'L'],
    isNew: true,
    celebrityCloset: true,
    occasions: ['Wedding', 'Reception'],
    discount: 30
  },
  {
    id: 'celebrity-1',
    name: 'Royal Brocade Sherwani Set',
    category: 'Men',
    price: 54000,
    image: '/images/celebrity/1774861981073groom-essentials.webp',
    badge: 'Celebrity Choice',
    description: 'A masterpiece brocade sherwani set worn by top actors during festive events. Created with hand-woven silk-zari patterns and tailored for an imposing presence.',
    highlights: ['Pure Silk Brocade base', 'Real gold-plated buttons', 'Tailored comfort fit', 'Includes matching silk stole'],
    designer: 'Manyavar Mohey',
    sizes: ['M', 'L', 'XL'],
    isNew: true,
    celebrityCloset: true,
    occasions: ['Wedding', 'Reception'],
    discount: 15
  },
  {
    id: 'celebrity-2',
    name: 'Golden Flora Lehenga Couture',
    category: 'Lehengas',
    price: 135000,
    image: '/images/celebrity/1773662540730multi-coloured-lehenga-edit.webp',
    badge: 'Showstopper Sensation',
    description: 'This showstopper fuchsia gold lehenga was designed specifically for celebrity wedding red carpets. Hand-embroidered with floral tilla threads and fine details.',
    highlights: ['Embellished with micro-pearls', 'Zardozi double borders', 'Extra volume flared skirt', 'Heavy sheer net dupatta'],
    designer: 'Ridhi Mehra',
    sizes: ['S', 'M', 'L'],
    isNew: false,
    celebrityCloset: true,
    occasions: ['Wedding'],
    discount: 10
  },
  {
    id: 'new-1',
    name: 'Mint Sharara Set',
    category: 'Women',
    price: 45000,
    image: '/images/whatsnew/1773662608426statement-sharara-sets.webp',
    badge: 'New Arrival',
    description: 'A refreshing mint-green sharara set featuring detailed mirror motifs and a matching silk dupatta. Light and perfect for morning ceremonies.',
    highlights: ['Premium georgette fabric', 'Reflective micro mirror yokes', 'Flared pleated trousers', 'Organza sheer border dupatta'],
    designer: 'Aza Editorials',
    sizes: ['XS', 'S', 'M', 'L'],
    isNew: true,
    celebrityCloset: false,
    occasions: ['Mehendi', 'Haldi'],
    discount: 12
  },
  {
    id: 'new-2',
    name: 'Mustard Kurta Haldi Edit',
    category: 'Men',
    price: 18000,
    image: '/images/whatsnew/1774861981073groom-essentials.webp',
    badge: 'Haldi Special',
    description: 'A soft premium khadi-silk kurta in vibrant mustard yellow, tailored specifically for wedding morning celebrations.',
    highlights: ['100% Breathable Khadi-Silk', 'Minimal tilla collar outlines', 'Lightweight and soft', 'Comes with cotton salwar pants'],
    designer: 'Playfair Mohey',
    sizes: ['S', 'M', 'L', 'XL'],
    isNew: true,
    celebrityCloset: false,
    occasions: ['Haldi'],
    discount: 18
  },
  {
    id: 'new-3',
    name: 'Pre-Stitched Floral Draped Saree',
    category: 'Wedding',
    price: 72000,
    image: '/images/whatsnew/1773662608426statement-sharara-sets.webp',
    badge: 'New Arrival',
    description: 'A hassle-free pre-stitched draped saree in soft pink, featuring gorgeous floral border appliques and an embellished blouse.',
    highlights: ['Pre-pleated layout drape', 'Concealed zipper waist', 'Comes with hand-beaded blouse', 'Crepe fluid fall fabric'],
    designer: 'Ridhi Mehra',
    sizes: ['S', 'M', 'L'],
    isNew: true,
    celebrityCloset: true,
    occasions: ['Reception'],
    discount: 22
  },
  {
    id: 'new-4',
    name: 'Emerald Mini Sherwani',
    category: 'Kids',
    price: 16800,
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
    badge: 'New Arrival',
    description: 'Classic emerald green miniature sherwani set for little boys. Extremely soft linings and comfortable child-friendly collars.',
    highlights: ['Organic child-safe lining', 'Soft thread work embroidery', 'Pre-tied elastic trousers', 'Dry clean only'],
    designer: 'Intimate Mohey',
    sizes: ['4-5 Yrs', '6-7 Yrs', '8-9 Yrs'],
    isNew: true,
    celebrityCloset: false,
    occasions: ['Wedding', 'Reception'],
    discount: 10
  }
];
